import { Activity, CircleAlert } from "lucide-react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { formatCurrency, formatNumber, formatPercent } from "@/lib/utils";
import type { AggregatedHolding } from "@/types/portfolio";

export function MutualFundNav({ holdings }: { holdings: AggregatedHolding[] }) {
  const funds = holdings.filter((holding) => holding.assetType === "mutual_fund");
  if (!funds.length) return null;
  return <Card><CardHeader><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Activity size={18} className="text-[var(--accent)]"/><h2 className="font-bold">Active mutual-fund NAV</h2></div><p className="mt-1 text-xs text-[var(--muted)]">Latest server-fetched NAV for held schemes</p></div><span className="rounded-full bg-[var(--accent-wash)] px-3 py-1 text-xs font-bold text-[var(--accent-strong)]">{funds.length} scheme{funds.length===1?"":"s"}</span></div></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{funds.map((fund)=><div key={fund.ticker} className="rounded-xl border bg-[var(--surface-2)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{fund.companyName}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{fund.ticker} · {formatNumber(fund.quantity,4)} units</p></div><span className={`whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-bold ${fund.quote?.stale?"bg-amber-100 text-amber-800":"bg-emerald-100 text-emerald-800"}`}>{fund.quote?.stale?<><CircleAlert className="mr-1 inline" size={11}/>Stale</>:"Active"}</span></div><div className="mt-4 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-wider text-[var(--muted)]">Current NAV</p><p className="mt-1 text-xl font-bold">{formatCurrency(fund.currentPrice)}</p></div><p className={`text-sm font-bold ${(fund.dayChangePercent??0)>=0?"text-emerald-700":"text-red-700"}`}>{formatPercent(fund.dayChangePercent)}</p></div><p className="mt-3 text-[10px] text-[var(--muted)]">As of {fund.quote?.marketTime?new Date(fund.quote.marketTime).toLocaleString("en-IN"):"unavailable"} · may be delayed</p></div>)}</div></CardContent></Card>;
}
